### ISSUE TITLE
Option to NOT attempt to download data

### ISSUE THREAD

**Issue by ljlamarche** [astib/MANGO#7]
Create a flag so mangopy will NOT attempt to download data from the ftp site if it is not found locally.  This would be a good way to handle a user making many plots of a night when certain cameras are not on.  If the user is sure they have all the available data, it is not helpful for mangopy to keep checking the server for files that do not exist.

**Comment by pmreyes2** [comment]
That would be very useful. I assume this is the function in question: [get_data](https://github.com/astib/MANGO/blob/b25cba78e58197394809cb8323656a1d636c3e3d/mangopy/mango.py#L64-L77) right?

**Comment by ljlamarche** [comment]
I believe so.  What we'd probably want to do is add an additional option to the except statement.
```
try:
    img_array, lat, lon, truetime = self.read_datafile(filename,targtime)
# if that fails, try to download, then read the data file
except (OSError, IOError):
############### POTENTIAL ADDITION ######################
    if download_data == False:
        ....
#######################################################
    print('Attempting to download {} from FTP server.'.format(os.path.basename(filename)))
    self.fetch_datafile(site, targtime.date())
img_array, lat, lon, truetime = self.read_datafile(filename,targtime)
```
However, the current usage of mangopy doen't really involve users using get_data directly (you just initialize Mango or Mosaic and it handles the rest from there), so we may have to put specification of whether or not to download data as an initialization option.  We probably also want to think about what exactly the desired behavior is.  If you specify to only use local data and mangopy can't find a particular file, should it raise an error or just do nothing?

**Comment by pmreyes2** [comment]
Well, one can have a list of the available data locally, and ideally also a list of the available data (that can be updated with a method `update_remote_list()`) in the server. Then there could be methods : `data_exists_locally()` and/or `data_exists_remotely()` before attempting to read or fetch data. Then, I agree that when initializing `Mango` or `Mosaic` we can pass a parameter `download_data=False` to avoid fetching data remotely. `self.download_data` can be used inside the `try/except` inside [get_data](https://github.com/astib/MANGO/blob/b25cba78e58197394809cb8323656a1d636c3e3d/mangopy/mango.py#L64-L77) . The `self.download_data` parameter could also be updated with a method.

**Comment by ljlamarche** [comment]
Finished.
