### ISSUE TITLE
[DISC]: loosen up the requirements.txt

### ISSUE THREAD

**Issue by asreimer** [astib/MANGO#8]
The requirements for this package seem overly strict, for example, `numpy >=1.16`. Are these really necessary? Perhaps we can loosen the restrictions a bit?

**Comment by ljlamarche** [comment]
This probably is excessively strict.  Is there any rule of thumb for how to handle these things, or should I just see how old of a numpy version I can have before things start to break?

**Comment by asreimer** [comment]
Here's some recommendations:

- **numpy >= 1.16**: Remove this. Matplotlib and scipy versions determine the version of numpy needed. 
- **h5py >= 2.9**: Looking at the [release history](https://docs.h5py.org/en/stable/whatsnew/index.html) this version looks fine. Going to older versions would only allow support for older versions of Python 3 (like 3.2), but it is unlikely anyone doing data analysis is using 3.2. Probably, we don't need to specify a version number.
- **matplotlib >= 2.2.4**: Looking at the [release history](https://matplotlib.org/stable/users/whats_new_old.html), 2.2.4 is probably fine, but I would recommend dropping the version number
- **cartopy >= 0.17**: Cartopy is a relatively new project, 0.17 is probably the oldest version I would recommend. I don't have a good reason for this, but I think specifying the version number here makes sense.
- **scipy >= 1.2**: mangopy is only using interpolate and convex hull code from scipy. I would change the minimum version to 0.17.
- **future >= 0.16**: Remove this. No one should be using Python 2 anymore. Numpy, matplotlib, scipy, etc don't support Python 2

**Comment by ljlamarche** [comment]
I ended up doing this in d584b4aa13672211d2854ba70a9cc9cae1eace9a as part of getting mangopy to build on readthedocs.  I adopted all of @asreimer's suggestions above except for cartopy.  When installing cartopy via pip, you have to first [manually install several dependancies](https://scitools.org.uk/cartopy/docs/latest/installing.html#building-from-source).  This isn't necessary when [installing cartopy with conda](https://scitools.org.uk/cartopy/docs/latest/installing.html#conda-pre-built-binaries).  If cartopy is included in `requirements.txt`, it produces build errors.  The README does specify that cartopy must be installed BEFORE mangopy, so I think it's fine to leave cartopy out of `requirements.txt`, and just make the installation instructions:
1. Install cartopy
2. Install mangopy
